{
  "status_code": 0,
  "comments": [
    {
      "cid": "7552459398330827527",
      "text": "انتہائی دکھ اور معذرت کے ساتھ ہنسی آرہی ہے 😭🤣🤣",
      "aweme_id": "7552116174754974998",
      "create_time": 1758443993,
      "digg_count": 36,
      "status": 1,
      "user": {
        "uid": "6872402959213364226",
        "short_id": "0",
        "nickname": "@⃟",
        "gender": 0,
        "signature": "From Kp 😋\nDir Lower 🌲\nخا ل   🥰",
        "avatar_thumb": {
          "uri": "tos-alisg-avt-0068/82ce25686f6282e0451308a829369175",
          "url_list": [
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/82ce25686f6282e0451308a829369175~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=ad3cdd9a&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=Z4Vqi%2B9h4tnZsh3LcU1su%2B8IP%2Fk%3D",
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/82ce25686f6282e0451308a829369175~tplv-tiktokx-cropcenter-q:100:100:q70.jpeg?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=c4d3f3f8&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=LJPKaSLi3jsNH9MiNRDZZOXK%2FvU%3D"
          ],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "birthday": "1900-01-01",
        "follow_status": 0,
        "aweme_count": 0,
        "following_count": 0,
        "follower_count": 0,
        "favoriting_count": 0,
        "total_favorited": 0,
        "is_block": false,
        "hide_search": false,
        "custom_verify": "",
        "unique_id": "h_l_yousafzai",
        "bind_phone": "",
        "special_lock": 1,
        "need_recommend": 0,
        "has_facebook_token": false,
        "has_twitter_token": false,
        "fb_expire_time": 0,
        "tw_expire_time": 0,
        "has_youtube_token": false,
        "youtube_expire_time": 0,
        "room_id": 0,
        "live_verify": 0,
        "authority_status": 0,
        "verify_info": "",
        "shield_follow_notice": 0,
        "shield_digg_notice": 0,
        "shield_comment_notice": 0,
        "with_commerce_entry": false,
        "verification_type": 1,
        "enterprise_verify_reason": "",
        "is_ad_fake": false,
        "followers_detail": null,
        "region": "PK",
        "account_region": "",
        "commerce_user_level": 0,
        "live_agreement": 0,
        "platform_sync_info": null,
        "with_shop_entry": false,
        "is_discipline_member": false,
        "secret": 0,
        "has_orders": false,
        "prevent_download": false,
        "show_image_bubble": false,
        "geofencing": [],
        "unique_id_modify_time": 1758669179,
        "video_icon": {
          "uri": "",
          "url_list": [],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "ins_id": "",
        "google_account": "",
        "youtube_channel_id": "",
        "youtube_channel_title": "",
        "apple_account": 0,
        "with_fusion_shop_entry": false,
        "is_phone_binded": false,
        "accept_private_policy": false,
        "twitter_id": "",
        "twitter_name": "",
        "user_canceled": false,
        "has_email": false,
        "live_agreement_time": 0,
        "status": 1,
        "create_time": 0,
        "avatar_uri": "tos-alisg-avt-0068/82ce25686f6282e0451308a829369175",
        "follower_status": 0,
        "comment_setting": 0,
        "duet_setting": 0,
        "reflow_page_gid": 0,
        "reflow_page_uid": 0,
        "user_rate": 1,
        "download_setting": 3,
        "download_prompt_ts": 1621725537,
        "react_setting": 3,
        "live_commerce": false,
        "cover_url": [
          {
            "uri": "tiktok-obj/1613727517271041",
            "url_list": [
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.image?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a",
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.jpeg?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a"
            ],
            "width": 720,
            "height": 720,
            "url_prefix": null
          }
        ],
        "language": "en",
        "has_insights": false,
        "item_list": null,
        "user_mode": 1,
        "user_period": 0,
        "is_star": false,
        "cv_level": "",
        "type_label": null,
        "ad_cover_url": null,
        "comment_filter_status": 0,
        "relative_users": null,
        "cha_list": null,
        "sec_uid": "MS4wLjABAAAA8q2ke_inl1LdFfEJaspbI2F-sD9mJLqy4QjM9APQQ4VZgJd5hrHSmrRz878KLHSU",
        "need_points": null,
        "homepage_bottom_toast": null,
        "can_set_geofencing": null,
        "white_cover_url": null,
        "user_tags": null,
        "stitch_setting": 0,
        "bold_fields": null,
        "search_highlight": null,
        "mutual_relation_avatars": null,
        "events": null,
        "predicted_age_group": "3",
        "advance_feature_item_order": null,
        "mention_status": 1,
        "special_account": {
          "special_account_list": null
        },
        "advanced_feature_info": null,
        "user_profile_guide": null,
        "shield_edit_field_info": null,
        "friends_status": 0,
        "can_message_follow_status_list": null,
        "matched_friend_available": false,
        "account_labels": null,
        "fake_data_info": {},
        "is_mute": 0,
        "reply_with_video_flag": 4,
        "user_spark_info": {},
        "is_mute_non_story_post": 0,
        "is_mute_story": 0,
        "is_mute_lives": 0,
        "enabled_filter_all_comments": false
      },
      "reply_id": "0",
      "user_digged": 0,
      "reply_comment": null,
      "text_extra": [],
      "reply_comment_total": 1,
      "reply_to_reply_id": "0",
      "is_author_digged": false,
      "stick_position": 0,
      "user_buried": false,
      "label_list": null,
      "author_pin": false,
      "no_show": false,
      "collect_stat": 0,
      "trans_btn_style": 1,
      "share_info": {
        "url": "https://m.tiktok.com/v/7552116174754974998.html?_d=c50db6l56flbei&comment_author_id=6872402959213364226&preview_pb=0&share_comment_id=7552459398330827527&share_item_id=7552116174754974998&sharer_language=en&source=h5_m&u_code=0",
        "acl": {
          "code": 1,
          "extra": "{\"item_share_acl\":\"empty item value\"}"
        },
        "desc": "@⃟’s comment: انتہائی دکھ اور معذرت کے ساتھ ہنسی آرہی ہے 😭🤣🤣",
        "title": "😭😭😭🥹🥹"
      },
      "comment_language": "ur",
      "image_list": null,
      "comment_post_item_ids": null,
      "is_comment_translatable": true,
      "sort_extra_score": {
        "reply_score": 0.000173,
        "show_more_score": 0.027922
      },
      "sort_tags": "{\"top_list\":1}",
      "is_high_purchase_intent": false,
      "allow_download_photo": true
    },
    {
      "cid": "7552244215918002945",
      "text": "ab hasna ha ya Rona ha 😂😭",
      "aweme_id": "7552116174754974998",
      "create_time": 1758393941,
      "digg_count": 175,
      "status": 1,
      "user": {
        "uid": "7111231523198370843",
        "short_id": "0",
        "nickname": "r🔞",
        "gender": 0,
        "signature": "😎handle with care🗿",
        "avatar_thumb": {
          "uri": "tos-alisg-avt-0068/dcf4959abd57f6aa177794a6c3d23ba9",
          "url_list": [
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/dcf4959abd57f6aa177794a6c3d23ba9~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=73c55ab2&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=7p%2FH8shSZhl%2FcVbiTfIJfFE6laE%3D",
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/dcf4959abd57f6aa177794a6c3d23ba9~tplv-tiktokx-cropcenter-q:100:100:q70.jpeg?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=1200ca4d&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=0F8qvkWIrYkw9ARmtPnNz4Y7jYo%3D"
          ],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "birthday": "1900-01-01",
        "follow_status": 0,
        "aweme_count": 0,
        "following_count": 0,
        "follower_count": 0,
        "favoriting_count": 0,
        "total_favorited": 0,
        "is_block": false,
        "hide_search": false,
        "custom_verify": "",
        "unique_id": "lifebackar",
        "bind_phone": "",
        "special_lock": 1,
        "need_recommend": 0,
        "has_facebook_token": false,
        "has_twitter_token": false,
        "fb_expire_time": 0,
        "tw_expire_time": 0,
        "has_youtube_token": false,
        "youtube_expire_time": 0,
        "room_id": 0,
        "live_verify": 0,
        "authority_status": 0,
        "verify_info": "",
        "shield_follow_notice": 0,
        "shield_digg_notice": 0,
        "shield_comment_notice": 0,
        "with_commerce_entry": false,
        "verification_type": 1,
        "enterprise_verify_reason": "",
        "is_ad_fake": false,
        "followers_detail": null,
        "region": "PK",
        "account_region": "",
        "commerce_user_level": 0,
        "live_agreement": 0,
        "platform_sync_info": null,
        "with_shop_entry": false,
        "is_discipline_member": false,
        "secret": 0,
        "has_orders": false,
        "prevent_download": false,
        "show_image_bubble": false,
        "geofencing": [],
        "unique_id_modify_time": 1758669179,
        "video_icon": {
          "uri": "",
          "url_list": [],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "ins_id": "",
        "google_account": "",
        "youtube_channel_id": "",
        "youtube_channel_title": "",
        "apple_account": 0,
        "with_fusion_shop_entry": false,
        "is_phone_binded": false,
        "accept_private_policy": false,
        "twitter_id": "",
        "twitter_name": "",
        "user_canceled": false,
        "has_email": false,
        "live_agreement_time": 0,
        "status": 1,
        "create_time": 0,
        "avatar_uri": "tos-alisg-avt-0068/dcf4959abd57f6aa177794a6c3d23ba9",
        "follower_status": 0,
        "comment_setting": 0,
        "duet_setting": 0,
        "reflow_page_gid": 0,
        "reflow_page_uid": 0,
        "user_rate": 1,
        "download_setting": 3,
        "download_prompt_ts": 1664158578,
        "react_setting": 0,
        "live_commerce": false,
        "cover_url": [
          {
            "uri": "tiktok-obj/1613727517271041",
            "url_list": [
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.image?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a",
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.jpeg?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a"
            ],
            "width": 720,
            "height": 720,
            "url_prefix": null
          }
        ],
        "language": "en",
        "has_insights": false,
        "item_list": null,
        "user_mode": 1,
        "user_period": 0,
        "is_star": false,
        "cv_level": "",
        "type_label": null,
        "ad_cover_url": null,
        "comment_filter_status": 0,
        "relative_users": null,
        "cha_list": null,
        "sec_uid": "MS4wLjABAAAAHvjxCsXvIOi1A_5qVGwv6_TLElZysXtZryySDbgtBtlvrgJ8je64rCD-4POaTXr2",
        "need_points": null,
        "homepage_bottom_toast": null,
        "can_set_geofencing": null,
        "white_cover_url": null,
        "user_tags": null,
        "stitch_setting": 0,
        "bold_fields": null,
        "search_highlight": null,
        "mutual_relation_avatars": null,
        "events": null,
        "predicted_age_group": "3",
        "advance_feature_item_order": null,
        "mention_status": 1,
        "special_account": {
          "special_account_list": null
        },
        "advanced_feature_info": null,
        "user_profile_guide": null,
        "shield_edit_field_info": null,
        "friends_status": 0,
        "can_message_follow_status_list": null,
        "matched_friend_available": false,
        "account_labels": null,
        "fake_data_info": {},
        "is_mute": 0,
        "reply_with_video_flag": 4,
        "user_spark_info": {},
        "is_mute_non_story_post": 0,
        "is_mute_story": 0,
        "is_mute_lives": 0,
        "enabled_filter_all_comments": false
      },
      "reply_id": "0",
      "user_digged": 0,
      "reply_comment": null,
      "text_extra": [],
      "reply_comment_total": 6,
      "reply_to_reply_id": "0",
      "is_author_digged": true,
      "stick_position": 0,
      "user_buried": false,
      "label_list": [
        {
          "type": 20,
          "text": "Liked by creator"
        }
      ],
      "author_pin": false,
      "no_show": false,
      "collect_stat": 0,
      "trans_btn_style": 0,
      "share_info": {
        "url": "https://m.tiktok.com/v/7552116174754974998.html?_d=c50db6l56flbei&comment_author_id=7111231523198370843&preview_pb=0&share_comment_id=7552244215918002945&share_item_id=7552116174754974998&sharer_language=en&source=h5_m&u_code=0",
        "acl": {
          "code": 1,
          "extra": "{\"item_share_acl\":\"empty item value\"}"
        },
        "desc": "r🔞’s comment: ab hasna ha ya Rona ha 😂😭",
        "title": "😭😭😭🥹🥹"
      },
      "comment_language": "en",
      "image_list": null,
      "comment_post_item_ids": null,
      "is_comment_translatable": true,
      "sort_extra_score": {
        "reply_score": 0.000091,
        "show_more_score": 0.030271
      },
      "sort_tags": "{\"author_digg\":1,\"top_list\":1}",
      "is_high_purchase_intent": false,
      "allow_download_photo": true
    },
    {
      "cid": "7552350563931276033",
      "text": "ماشاءاللہ آپ پاس ہو گے ہیں\n45 دن بعد آنا اپنا لائسنس لے جانا 😁😁😁",
      "aweme_id": "7552116174754974998",
      "create_time": 1758418660,
      "digg_count": 142,
      "status": 1,
      "user": {
        "uid": "7520884790372140049",
        "short_id": "0",
        "nickname": "Ch Brand123",
        "gender": 0,
        "signature": "",
        "avatar_thumb": {
          "uri": "tos-alisg-avt-0068/5d6a8bea3e7767f2b105feeb44fa5bed",
          "url_list": [
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/5d6a8bea3e7767f2b105feeb44fa5bed~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=1b69b4ed&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=XgqLk9c9h%2B%2FNnhvNcmxRV%2FYthAs%3D",
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/5d6a8bea3e7767f2b105feeb44fa5bed~tplv-tiktokx-cropcenter-q:100:100:q70.jpeg?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=3b8d7182&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=dHdROnTmLyxE4kPgADUNBSVzKrs%3D"
          ],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "birthday": "1900-01-01",
        "follow_status": 0,
        "aweme_count": 0,
        "following_count": 0,
        "follower_count": 0,
        "favoriting_count": 0,
        "total_favorited": 0,
        "is_block": false,
        "hide_search": false,
        "custom_verify": "",
        "unique_id": "ch.brand1233",
        "bind_phone": "",
        "special_lock": 1,
        "need_recommend": 0,
        "has_facebook_token": false,
        "has_twitter_token": false,
        "fb_expire_time": 0,
        "tw_expire_time": 0,
        "has_youtube_token": false,
        "youtube_expire_time": 0,
        "room_id": 0,
        "live_verify": 0,
        "authority_status": 0,
        "verify_info": "",
        "shield_follow_notice": 0,
        "shield_digg_notice": 0,
        "shield_comment_notice": 0,
        "with_commerce_entry": false,
        "verification_type": 1,
        "enterprise_verify_reason": "",
        "is_ad_fake": false,
        "followers_detail": null,
        "region": "SA",
        "account_region": "",
        "commerce_user_level": 0,
        "live_agreement": 0,
        "platform_sync_info": null,
        "with_shop_entry": false,
        "is_discipline_member": false,
        "secret": 0,
        "has_orders": false,
        "prevent_download": false,
        "show_image_bubble": false,
        "geofencing": [],
        "unique_id_modify_time": 1758669179,
        "video_icon": {
          "uri": "",
          "url_list": [],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "ins_id": "",
        "google_account": "",
        "youtube_channel_id": "",
        "youtube_channel_title": "",
        "apple_account": 0,
        "with_fusion_shop_entry": false,
        "is_phone_binded": false,
        "accept_private_policy": false,
        "twitter_id": "",
        "twitter_name": "",
        "user_canceled": false,
        "has_email": false,
        "live_agreement_time": 0,
        "status": 1,
        "create_time": 0,
        "avatar_uri": "tos-alisg-avt-0068/5d6a8bea3e7767f2b105feeb44fa5bed",
        "follower_status": 0,
        "comment_setting": 0,
        "duet_setting": 0,
        "reflow_page_gid": 0,
        "reflow_page_uid": 0,
        "user_rate": 1,
        "download_setting": 0,
        "download_prompt_ts": 1754782913,
        "react_setting": 0,
        "live_commerce": false,
        "cover_url": [
          {
            "uri": "tiktok-obj/1613727517271041",
            "url_list": [
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.image?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a",
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.jpeg?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a"
            ],
            "width": 720,
            "height": 720,
            "url_prefix": null
          }
        ],
        "language": "en",
        "has_insights": false,
        "item_list": null,
        "user_mode": 1,
        "user_period": 0,
        "is_star": false,
        "cv_level": "",
        "type_label": null,
        "ad_cover_url": null,
        "comment_filter_status": 0,
        "relative_users": null,
        "cha_list": null,
        "sec_uid": "MS4wLjABAAAAq-U79O5KDSQjVc3ci4nCeA597q8TzNiJpd9o5C5a-lm8LzHmUMcZMZxmS_5NUhtN",
        "need_points": null,
        "homepage_bottom_toast": null,
        "can_set_geofencing": null,
        "white_cover_url": null,
        "user_tags": null,
        "stitch_setting": 0,
        "bold_fields": null,
        "search_highlight": null,
        "mutual_relation_avatars": null,
        "events": null,
        "predicted_age_group": "",
        "advance_feature_item_order": null,
        "mention_status": 1,
        "special_account": {
          "special_account_list": null
        },
        "advanced_feature_info": null,
        "user_profile_guide": null,
        "shield_edit_field_info": null,
        "friends_status": 0,
        "can_message_follow_status_list": null,
        "matched_friend_available": false,
        "account_labels": null,
        "fake_data_info": {},
        "is_mute": 0,
        "reply_with_video_flag": 4,
        "user_spark_info": {},
        "is_mute_non_story_post": 0,
        "is_mute_story": 0,
        "is_mute_lives": 0,
        "enabled_filter_all_comments": false
      },
      "reply_id": "0",
      "user_digged": 0,
      "reply_comment": [
        {
          "cid": "7552370827509891862",
          "text": "😂",
          "aweme_id": "7552116174754974998",
          "create_time": 1758423413,
          "digg_count": 8,
          "status": 1,
          "user": {
            "uid": "7530883450845512726",
            "short_id": "0",
            "nickname": "labaqueen5",
            "gender": 0,
            "signature": "Fateh pur love \n❤️",
            "avatar_thumb": {
              "uri": "tos-no1a-avt-0068c001-no/79f582ba4e5fad6fb464b0a0509f0a1f",
              "url_list": [
                "https://p16-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/79f582ba4e5fad6fb464b0a0509f0a1f~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=8e801bb3&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=1qX7CSA8pW4tiE%2BO5cZiwDTdYcg%3D",
                "https://p19-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/79f582ba4e5fad6fb464b0a0509f0a1f~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=4c528cf8&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=ICdho9I8Nr1moOVf7lQ5sn08EBs%3D",
                "https://p16-pu-sign-no.tiktokcdn-eu.com/tos-no1a-avt-0068c001-no/79f582ba4e5fad6fb464b0a0509f0a1f~tplv-tiktokx-cropcenter-q:100:100:q70.jpeg?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=a943db03&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=cv4A%2BQ3pvVyd%2BWh0fb%2BpdYrAmyU%3D"
              ],
              "width": 720,
              "height": 720,
              "url_prefix": null
            },
            "birthday": "1900-01-01",
            "follow_status": 0,
            "aweme_count": 0,
            "following_count": 0,
            "follower_count": 0,
            "favoriting_count": 0,
            "total_favorited": 0,
            "is_block": false,
            "hide_search": false,
            "custom_verify": "",
            "unique_id": "labaqueen5",
            "bind_phone": "",
            "special_lock": 1,
            "need_recommend": 0,
            "has_facebook_token": false,
            "has_twitter_token": false,
            "fb_expire_time": 0,
            "tw_expire_time": 0,
            "has_youtube_token": false,
            "youtube_expire_time": 0,
            "room_id": 0,
            "live_verify": 0,
            "authority_status": 0,
            "verify_info": "",
            "shield_follow_notice": 0,
            "shield_digg_notice": 0,
            "shield_comment_notice": 0,
            "with_commerce_entry": false,
            "verification_type": 1,
            "enterprise_verify_reason": "",
            "is_ad_fake": false,
            "followers_detail": null,
            "region": "PK",
            "account_region": "",
            "commerce_user_level": 0,
            "live_agreement": 0,
            "platform_sync_info": null,
            "with_shop_entry": false,
            "is_discipline_member": false,
            "secret": 0,
            "has_orders": false,
            "prevent_download": false,
            "show_image_bubble": false,
            "geofencing": [],
            "unique_id_modify_time": 1758669179,
            "video_icon": {
              "uri": "",
              "url_list": [],
              "width": 720,
              "height": 720,
              "url_prefix": null
            },
            "ins_id": "",
            "google_account": "",
            "youtube_channel_id": "",
            "youtube_channel_title": "",
            "apple_account": 0,
            "with_fusion_shop_entry": false,
            "is_phone_binded": false,
            "accept_private_policy": false,
            "twitter_id": "",
            "twitter_name": "",
            "user_canceled": false,
            "has_email": false,
            "live_agreement_time": 0,
            "status": 1,
            "create_time": 0,
            "avatar_uri": "tos-no1a-avt-0068c001-no/79f582ba4e5fad6fb464b0a0509f0a1f",
            "follower_status": 0,
            "comment_setting": 0,
            "duet_setting": 0,
            "reflow_page_gid": 0,
            "reflow_page_uid": 0,
            "user_rate": 1,
            "download_setting": 0,
            "download_prompt_ts": 1753430093,
            "react_setting": 0,
            "live_commerce": false,
            "cover_url": [
              {
                "uri": "tiktok-obj/1613727517271041",
                "url_list": [
                  "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.image?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a",
                  "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.jpeg?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a"
                ],
                "width": 720,
                "height": 720,
                "url_prefix": null
              }
            ],
            "language": "en",
            "has_insights": false,
            "item_list": null,
            "user_mode": 1,
            "user_period": 0,
            "is_star": false,
            "cv_level": "",
            "type_label": null,
            "ad_cover_url": null,
            "comment_filter_status": 0,
            "relative_users": null,
            "cha_list": null,
            "sec_uid": "MS4wLjABAAAApljsIiTxz3t81Cqk5DUPMT2H_1rc7qCnaJ2Cd90XQJKkJiqqU5E18ExkT75qfcL6",
            "need_points": null,
            "homepage_bottom_toast": null,
            "can_set_geofencing": null,
            "white_cover_url": null,
            "user_tags": null,
            "stitch_setting": 0,
            "bold_fields": null,
            "search_highlight": null,
            "mutual_relation_avatars": null,
            "events": null,
            "predicted_age_group": "",
            "advance_feature_item_order": null,
            "mention_status": 1,
            "special_account": {
              "special_account_list": null
            },
            "advanced_feature_info": null,
            "user_profile_guide": null,
            "shield_edit_field_info": null,
            "friends_status": 0,
            "can_message_follow_status_list": null,
            "matched_friend_available": false,
            "account_labels": null,
            "fake_data_info": {},
            "is_mute": 0,
            "reply_with_video_flag": 4,
            "user_spark_info": {},
            "is_mute_non_story_post": 0,
            "is_mute_story": 0,
            "is_mute_lives": 0,
            "enabled_filter_all_comments": false
          },
          "reply_id": "7552350563931276033",
          "user_digged": 0,
          "reply_comment": null,
          "text_extra": [],
          "label_text": "Creator",
          "label_type": 1,
          "reply_to_reply_id": "0",
          "is_author_digged": false,
          "stick_position": 0,
          "user_buried": false,
          "label_list": [
            {
              "type": 1,
              "text": "Creator"
            }
          ],
          "author_pin": false,
          "no_show": false,
          "collect_stat": 0,
          "trans_btn_style": 0,
          "share_info": {
            "url": "https://m.tiktok.com/v/7552116174754974998.html?_d=c50db6l56flbei&comment_author_id=7530883450845512726&preview_pb=0&share_comment_id=7552370827509891862&share_item_id=7552116174754974998&sharer_language=en&source=h5_m&u_code=0",
            "acl": {
              "code": 1,
              "extra": "{\"item_share_acl\":\"empty item value\"}"
            },
            "desc": "labaqueen5’s comment: 😂",
            "title": "😭😭😭🥹🥹"
          },
          "comment_language": "un",
          "image_list": null,
          "comment_post_item_ids": null,
          "is_comment_translatable": false,
          "is_high_purchase_intent": false,
          "allow_download_photo": true
        }
      ],
      "text_extra": [],
      "reply_comment_total": 8,
      "reply_to_reply_id": "0",
      "is_author_digged": true,
      "stick_position": 0,
      "user_buried": false,
      "label_list": [
        {
          "type": 20,
          "text": "Liked by creator"
        }
      ],
      "author_pin": false,
      "no_show": false,
      "collect_stat": 0,
      "trans_btn_style": 1,
      "share_info": {
        "url": "https://m.tiktok.com/v/7552116174754974998.html?_d=c50db6l56flbei&comment_author_id=7520884790372140049&preview_pb=0&share_comment_id=7552350563931276033&share_item_id=7552116174754974998&sharer_language=en&source=h5_m&u_code=0",
        "acl": {
          "code": 1,
          "extra": "{\"item_share_acl\":\"empty item value\"}"
        },
        "desc": "Ch Brand123’s comment: ماشاءاللہ آپ پاس ہو گے ہیں\n45 دن بعد آنا اپنا لائسنس لے جانا 😁😁😁",
        "title": "😭😭😭🥹🥹"
      },
      "comment_language": "ur",
      "image_list": null,
      "comment_post_item_ids": null,
      "is_comment_translatable": true,
      "sort_extra_score": {
        "reply_score": 0.000083,
        "show_more_score": 0.01883
      },
      "sort_tags": "{\"author_digg\":1,\"author_reply\":1,\"top_list\":1}",
      "is_high_purchase_intent": false,
      "allow_download_photo": true
    },
    {
      "cid": "7552448853653127957",
      "text": "yah gadi India kabadi walon ke pass hoti hai",
      "aweme_id": "7552116174754974998",
      "create_time": 1758441537,
      "digg_count": 1,
      "status": 1,
      "user": {
        "uid": "7527405738580182034",
        "short_id": "0",
        "nickname": "Parvej Khan",
        "gender": 0,
        "signature": "madina",
        "avatar_thumb": {
          "uri": "tos-alisg-avt-0068/b0293719de86b6ea4b5eaa9a05ebc64d",
          "url_list": [
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/b0293719de86b6ea4b5eaa9a05ebc64d~tplv-tiktokx-cropcenter-q:100:100:q70.webp?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=5c848e68&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=gieIERtXMWHOoRFIs4eEgcc1JKQ%3D",
            "https://p77-sign-sg.tiktokcdn.com/tos-alisg-avt-0068/b0293719de86b6ea4b5eaa9a05ebc64d~tplv-tiktokx-cropcenter-q:100:100:q70.jpeg?dr=9606&idc=no1a&ps=87d6e48a&refresh_token=ee93b744&s=COMMENT_LIST&sc=avatar&shcp=ff37627b&shp=30310797&t=223449c4&x-expires=1758754800&x-signature=qAHwkYQTPh0omMZbCLGn8cAWsqc%3D"
          ],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "birthday": "1900-01-01",
        "follow_status": 0,
        "aweme_count": 0,
        "following_count": 0,
        "follower_count": 0,
        "favoriting_count": 0,
        "total_favorited": 0,
        "is_block": false,
        "hide_search": false,
        "custom_verify": "",
        "unique_id": "parvej.khan0316",
        "bind_phone": "",
        "special_lock": 1,
        "need_recommend": 0,
        "has_facebook_token": false,
        "has_twitter_token": false,
        "fb_expire_time": 0,
        "tw_expire_time": 0,
        "has_youtube_token": false,
        "youtube_expire_time": 0,
        "room_id": 0,
        "live_verify": 0,
        "authority_status": 0,
        "verify_info": "",
        "shield_follow_notice": 0,
        "shield_digg_notice": 0,
        "shield_comment_notice": 0,
        "with_commerce_entry": false,
        "verification_type": 1,
        "enterprise_verify_reason": "",
        "is_ad_fake": false,
        "followers_detail": null,
        "region": "IN",
        "account_region": "",
        "commerce_user_level": 0,
        "live_agreement": 0,
        "platform_sync_info": null,
        "with_shop_entry": false,
        "is_discipline_member": false,
        "secret": 0,
        "has_orders": false,
        "prevent_download": false,
        "show_image_bubble": false,
        "geofencing": [],
        "unique_id_modify_time": 1758669179,
        "video_icon": {
          "uri": "",
          "url_list": [],
          "width": 720,
          "height": 720,
          "url_prefix": null
        },
        "ins_id": "",
        "google_account": "",
        "youtube_channel_id": "",
        "youtube_channel_title": "",
        "apple_account": 0,
        "with_fusion_shop_entry": false,
        "is_phone_binded": false,
        "accept_private_policy": false,
        "twitter_id": "",
        "twitter_name": "",
        "user_canceled": false,
        "has_email": false,
        "live_agreement_time": 0,
        "status": 1,
        "create_time": 0,
        "avatar_uri": "tos-alisg-avt-0068/b0293719de86b6ea4b5eaa9a05ebc64d",
        "follower_status": 0,
        "comment_setting": 0,
        "duet_setting": 0,
        "reflow_page_gid": 0,
        "reflow_page_uid": 0,
        "user_rate": 1,
        "download_setting": 0,
        "download_prompt_ts": 1752611915,
        "react_setting": 0,
        "live_commerce": false,
        "cover_url": [
          {
            "uri": "tiktok-obj/1613727517271041",
            "url_list": [
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.image?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a",
              "https://p77-sg.tiktokcdn.com/tiktok-obj/1613727517271041~tplv-tiktokx-origin.jpeg?dr=10423&t=4d5b0474&ps=933b5bde&shp=30310797&shcp=ff37627b&idc=no1a"
            ],
            "width": 720,
            "height": 720,
            "url_prefix": null
          }
        ],
        "language": "en",
        "has_insights": false,
        "item_list": null,
        "user_mode": 1,
        "user_period": 0,
        "is_star": false,
        "cv_level": "",
        "type_label": null,
        "ad_cover_url": null,
        "comment_filter_status": 0,
        "relative_users": null,
        "cha_list": null,
        "sec_uid": "MS4wLjABAAAATQO11AeMEjHTD_YCdYqQQhwIu38xW_iqD3m9k-nWBiMGwPc4q3bIWJ52McHbRqwt",
        "need_points": null,
        "homepage_bottom_toast": null,
        "can_set_geofencing": null,
        "white_cover_url": null,
        "user_tags": null,
        "stitch_setting": 0,
        "bold_fields": null,
        "search_highlight": null,
        "mutual_relation_avatars": null,
        "events": null,
        "predicted_age_group": "",
        "advance_feature_item_order": null,
        "mention_status": 1,
        "special_account": {
          "special_account_list": null
        },
        "advanced_feature_info": null,
        "user_profile_guide": null,
        "shield_edit_field_info": null,
        "friends_status": 0,
        "can_message_follow_status_list": null,
        "matched_friend_available": false,
        "account_labels": null,
        "fake_data_info": {},
        "is_mute": 0,
        "reply_with_video_flag": 4,
        "user_spark_info": {},
        "is_mute_non_story_post": 0,
        "is_mute_story": 0,
        "is_mute_lives": 0,
        "enabled_filter_all_comments": false
      },
      "reply_id": "0",
      "user_digged": 0,
      "reply_comment": null,
      "text_extra": [],
      "reply_comment_total": 2,
      "reply_to_reply_id": "0",
      "is_author_digged": false,
      "stick_position": 0,
      "user_buried": false,
      "label_list": null,
      "author_pin": false,
      "no_show": false,
      "collect_stat": 0,
      "trans_btn_style": 1,
      "share_info": {
        "url": "https://m.tiktok.com/v/7552116174754974998.html?_d=c50db6l56flbei&comment_author_id=7527405738580182034&preview_pb=0&share_comment_id=7552448853653127957&share_item_id=7552116174754974998&sharer_language=en&source=h5_m&u_code=0",
        "acl": {
          "code": 1,
          "extra": "{\"item_share_acl\":\"empty item value\"}"
        },
        "desc": "Parvej Khan’s comment: yah gadi India kabadi walon ke pass hoti hai",
        "title": "😭😭😭🥹🥹"
      },
      "comment_language": "hi",
      "image_list": null,
      "comment_post_item_ids": null,
      "is_comment_translatable": true,
      "sort_extra_score": {
        "reply_score": 0.000043,
        "show_more_score": 0.023334
      },
      "sort_tags": "{\"top_list\":1}",
      "is_high_purchase_intent": false,
      "allow_download_photo": true
    }
  ],
  "cursor": 5,
  "has_more": 1,
  "reply_style": 2,
  "total": 431,
  "extra": {
    "now": 1758669179000,
    "fatal_item_ids": null,
    "api_debug_info": null
  },
  "log_pb": {
    "impr_id": "2025092323125953D1ECBCC7A34D2EEAE4"
  },
  "top_gifts": null,
  "has_filtered_comments": 0,
  "alias_comment_deleted": false,
  "status_msg": ""
}
